name: Tests

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: rust ${{ matrix.rust-version }}
    strategy:
      matrix:
        include:
          - rust-version: stable
          - rust-version: 1.58
    steps:
      - uses: actions/checkout@v3

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          default: true

      - name: run tests
        run: cargo test
